name: FeedlessSafari
options:
  bundleIdPrefix: com.mattwagner.feedless-safari
  deploymentTarget:
    iOS: "15.0"
    macOS: "13.0"
  createIntermediateGroups: false
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.0"
    CLANG_ENABLE_OBJC_ARC: YES
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: PFT954M73N

configs:
  Debug: debug
  Release: release

targets:
  FeedlessSafari macOS:
    type: application
    platform: macOS
    settings:
      base:
        PRODUCT_NAME: FeedlessSafari
        PRODUCT_BUNDLE_IDENTIFIER: com.mattwagner.feedless-safari
        CODE_SIGN_STYLE: Automatic
        COMBINE_HIDPI_IMAGES: YES
        INFOPLIST_FILE: "macOS (App)/Info.plist"
        CODE_SIGN_ENTITLEMENTS: "macOS (App)/FeedlessSafari.entitlements"
    info:
      path: macOS (App)/Info.plist
    sources:
      - path: Shared (App)
      - path: macOS (App)
    dependencies:
      - target: FeedlessSafari macOS Extension
        embed: true
        codeSignOnCopy: true
        removeHeadersOnCopy: true

  FeedlessSafari iOS:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: FeedlessSafari
        PRODUCT_BUNDLE_IDENTIFIER: com.mattwagner.feedless-safari
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "iOS (App)/Info.plist"
        CODE_SIGN_ENTITLEMENTS: "iOS (App)/FeedlessSafari.entitlements"
    info:
      path: iOS (App)/Info.plist
    sources:
      - path: Shared (App)
      - path: iOS (App)
    dependencies:
      - target: FeedlessSafari iOS Extension
        embed: true
        codeSignOnCopy: true
        removeHeadersOnCopy: true

  FeedlessSafari macOS Extension:
    type: app-extension
    platform: macOS
    settings:
      base:
        PRODUCT_NAME: "FeedlessSafari Extension"
        PRODUCT_BUNDLE_IDENTIFIER: com.mattwagner.feedless-safari.Extension
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: "macOS (Extension)/Info.plist"
        CODE_SIGN_ENTITLEMENTS: "macOS (Extension)/FeedlessSafariExtension.entitlements"
    info:
      path: macOS (Extension)/Info.plist
      properties:
        CFBundlePackageType: XPC!
        NSExtension:
          NSExtensionPointIdentifier: com.apple.Safari.web-extension
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).SafariWebExtensionHandler
    sources:
      - path: Shared (Extension)
        excludes:
          - "Resources/**"
      - path: Shared (App)/SharedDefaults.swift
      - path: Shared (Extension)/Resources/assets
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/chunks
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/content-scripts
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/icons
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/background.js
        buildPhase: resources
      - path: Shared (Extension)/Resources/bridge.js
        buildPhase: resources
      - path: Shared (Extension)/Resources/icon.svg
        buildPhase: resources
      - path: Shared (Extension)/Resources/manifest.json
        buildPhase: resources
      - path: Shared (Extension)/Resources/options.html
        buildPhase: resources
      - path: Shared (Extension)/Resources/popup.html
        buildPhase: resources
    dependencies:
      - sdk: SafariServices.framework

  FeedlessSafari iOS Extension:
    type: app-extension
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: "FeedlessSafari Extension"
        PRODUCT_BUNDLE_IDENTIFIER: com.mattwagner.feedless-safari.Extension
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_FILE: "iOS (Extension)/Info.plist"
        CODE_SIGN_ENTITLEMENTS: "iOS (Extension)/FeedlessSafariExtension.entitlements"
    info:
      path: iOS (Extension)/Info.plist
      properties:
        CFBundlePackageType: XPC!
        NSExtension:
          NSExtensionPointIdentifier: com.apple.Safari.web-extension
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).SafariWebExtensionHandler
    sources:
      - path: Shared (Extension)
        excludes:
          - "Resources/**"
      - path: Shared (App)/SharedDefaults.swift
      - path: Shared (Extension)/Resources/assets
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/chunks
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/content-scripts
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/icons
        type: folder
        buildPhase: resources
      - path: Shared (Extension)/Resources/background.js
        buildPhase: resources
      - path: Shared (Extension)/Resources/bridge.js
        buildPhase: resources
      - path: Shared (Extension)/Resources/icon.svg
        buildPhase: resources
      - path: Shared (Extension)/Resources/manifest.json
        buildPhase: resources
      - path: Shared (Extension)/Resources/options.html
        buildPhase: resources
      - path: Shared (Extension)/Resources/popup.html
        buildPhase: resources
