// Feedless Safari — curated quote library for the quote widget.
// Public-domain sources only (ancient authors or works published before 1929).
// Curated independently; not copied from any other project's quote data.
window.__feedlessQuotes = [
  { text: "You have power over your mind — not outside events. Realize this, and you will find strength.", attribution: "Marcus Aurelius" },
  { text: "The happiness of your life depends upon the quality of your thoughts.", attribution: "Marcus Aurelius" },
  { text: "Confine yourself to the present.", attribution: "Marcus Aurelius" },
  { text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.", attribution: "Marcus Aurelius" },
  { text: "Waste no more time arguing about what a good man should be. Be one.", attribution: "Marcus Aurelius" },
  { text: "If it is not right do not do it; if it is not true do not say it.", attribution: "Marcus Aurelius" },
  { text: "The impediment to action advances action. What stands in the way becomes the way.", attribution: "Marcus Aurelius" },
  { text: "It is not that we have a short time to live, but that we waste a lot of it.", attribution: "Seneca" },
  { text: "While we are postponing, life speeds by.", attribution: "Seneca" },
  { text: "They lose the day in expectation of the night, and the night in fear of the dawn.", attribution: "Seneca" },
  { text: "Begin at once to live, and count each separate day as a separate life.", attribution: "Seneca" },
  { text: "Nothing is a better proof of a well-ordered mind than a man's ability to stop just where he is and pass some time in his own company.", attribution: "Seneca" },
  { text: "Wealth consists not in having great possessions, but in having few wants.", attribution: "Epictetus" },
  { text: "First say to yourself what you would be; and then do what you have to do.", attribution: "Epictetus" },
  { text: "No man is free who is not master of himself.", attribution: "Epictetus" },
  { text: "Don't explain your philosophy. Embody it.", attribution: "Epictetus" },
  { text: "Do not spoil what you have by desiring what you have not.", attribution: "Epicurus" },
  { text: "To do two things at once is to do neither.", attribution: "Publilius Syrus" },
  { text: "Seize the day, put very little trust in tomorrow.", attribution: "Horace" },
  { text: "Take rest; a field that has rested gives a bountiful crop.", attribution: "Ovid" },
  { text: "If you have a garden and a library, you have everything you need.", attribution: "Cicero" },
  { text: "The first and greatest victory is to conquer yourself.", attribution: "Plato" },
  { text: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", attribution: "Will Durant, on Aristotle" },
  { text: "Nature does not hurry, yet everything is accomplished.", attribution: "Lao Tzu" },
  { text: "When I let go of what I am, I become what I might be.", attribution: "Lao Tzu" },
  { text: "It does not matter how slowly you go as long as you do not stop.", attribution: "Confucius" },
  { text: "The man who moves a mountain begins by carrying away small stones.", attribution: "Confucius" },
  { text: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", attribution: "attributed to the Buddha" },
  { text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.", attribution: "Blaise Pascal" },
  { text: "The greatest thing in the world is to know how to belong to oneself.", attribution: "Michel de Montaigne" },
  { text: "Those who make the worst use of their time are the first to complain of its brevity.", attribution: "Jean de La Bruyère" },
  { text: "Time stays long enough for anyone who will use it.", attribution: "Leonardo da Vinci" },
  { text: "Simplicity is the ultimate sophistication.", attribution: "attributed to Leonardo da Vinci" },
  { text: "Things which matter most must never be at the mercy of things which matter least.", attribution: "Johann Wolfgang von Goethe" },
  { text: "Nothing is worth more than this day.", attribution: "Johann Wolfgang von Goethe" },
  { text: "Dost thou love life? Then do not squander time, for that is the stuff life is made of.", attribution: "Benjamin Franklin" },
  { text: "Lost time is never found again.", attribution: "Benjamin Franklin" },
  { text: "Well done is better than well said.", attribution: "Benjamin Franklin" },
  { text: "Never put off till tomorrow what you can do today.", attribution: "Thomas Jefferson" },
  { text: "Procrastination is the thief of time.", attribution: "Edward Young" },
  { text: "What we hope ever to do with ease, we may learn first to do with diligence.", attribution: "Samuel Johnson" },
  { text: "Ordinary people think merely of spending time; great people think of using it.", attribution: "attributed to Arthur Schopenhauer" },
  { text: "It is not enough to be busy; so are the ants. The question is: what are we busy about?", attribution: "Henry David Thoreau" },
  { text: "Our life is frittered away by detail. Simplify, simplify.", attribution: "Henry David Thoreau" },
  { text: "As if you could kill time without injuring eternity.", attribution: "Henry David Thoreau" },
  { text: "The price of anything is the amount of life you exchange for it.", attribution: "attributed to Henry David Thoreau" },
  { text: "Guard well your spare moments.", attribution: "Ralph Waldo Emerson" },
  { text: "Concentration is the secret of strength.", attribution: "Ralph Waldo Emerson" },
  { text: "The only person you are destined to become is the person you decide to be.", attribution: "attributed to Ralph Waldo Emerson" },
  { text: "The art of being wise is the art of knowing what to overlook.", attribution: "William James" },
  { text: "Act as if what you do makes a difference. It does.", attribution: "William James" },
  { text: "The secret of getting ahead is getting started.", attribution: "attributed to Mark Twain" },
  { text: "Comparison is the death of joy.", attribution: "attributed to Mark Twain" },
  { text: "The two most powerful warriors are patience and time.", attribution: "Leo Tolstoy" },
  { text: "True life is lived when tiny changes occur.", attribution: "Leo Tolstoy" },
  { text: "It is never too late to be what you might have been.", attribution: "attributed to George Eliot" },
];
